name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Or the branch you're deploying from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Use a stable Ruby version compatible with Jekyll

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
